name: Publish package

on:
  release:
    types: ['created']

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish-vscode-marketplace
    permissions:
      contents: write
      id-token: write # required for OIDC token
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: 'npm'
      - run: npm ci
      - name: Set version from a tag
        run: npm version --no-git-tag-version ${{ github.event.release.tag_name }}
      - name: Package
        run: npm run package
      - name: Azure login (user-assigned managed identity)
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true
      - name: Publish to VS Code Marketplace
        run: npx @vscode/vsce publish --azure-credential --packagePath ./*.vsix
      - name: Upload VSIX to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} ./*.vsix
